#regix 正则表达式
import re
m = re.findall(".","aa\nabbcc")
print (m)
m = re.findall("\.","a.c")
print (m)
m = re.findall("a[bcd]e","abeaceade")
print (m)
m = re.findall("\d","abc1ab2c")
print (m)
m = re.findall("\D","abc1ab2c")
print (m)
m = re.findall("\s","abc a\tb2c")
print (m)
m = re.findall("\S","abc a\tb2c")
print (m)
m = re.findall("\w","alan#123#--")
print (m)
m = re.findall("\W","alan#123#--")
print (m)
m = re.findall("^abc","abcabc")
print (m)
m = re.findall("abc$","abcabc")
print (m)